[build-system]
requires = ["setuptools>=62.6"]
build-backend = "setuptools.build_meta"

[project]
name = "transactions-pipeline-7cefdc"
version = "0.1.0"
description = "ML training pipeline package"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "joblib==1.6.0",
    "numpy==2.2.6",
    "pandas==2.3.3",
    "scikit-learn==1.7.2",
    "scipy==1.15.3",
 ]

[project.scripts]
transactions-pipeline = "transactions_pipeline.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

